export const LIMIT_ALTERNATIVE = 50;
export const OFFSET_ALTERNATIVE = 0;
export const EnvConfiguration = () => ({
    SECRET_KEY: process.env.SECRET_KEY || 'SecretKey',
    NODE_ENV: process.env.NODE_ENV || 'development',
    MONGO_CONNECTION_URI: process.env.MONGO_CONNECTION_URI,
    MONGO_USER_DEVELOPMENT: process.env.MONGO_USER_DEVELOPMENT,
    MONGO_PASSWORD_DEVELOPMENT: process.env.MONGO_PASSWORD_DEVELOPMENT,
    MONGO_TEST_CONNECTION_URI: process.env.MONGO_TEST_CONNECTION_URI,
    MONGO_USER_TEST: process.env.MONGO_USER_TEST,
    MONGO_PASSWORD_TEST: process.env.MONGO_PASSWORD_TEST,
    AUTH_SOURCE_DEVELOPMENT: process.env.AUTH_SOURCE_DEVELOPMENT,
    AUTH_SOURCE_TEST: process.env.AUTH_SOURCE_TEST,
    LIMIT: +process.env.LIMIT || LIMIT_ALTERNATIVE,
    OFFSET: +process.env.OFFSET || OFFSET_ALTERNATIVE,
});
